version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name: challenge-7
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: agung
      POSTGRES_PASSWORD: car-management_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
